WorldEvents:
  SolarEclipse:
    Enabled: true
    Frequency: 20
    Factor: 0.0
    Element: Fire
    Time: Day
  LunarEclipse:
    Enabled: true
    Frequency: 40
    Factor: 0.0
    Element: Water
    Time: Night
  SozinsComet:
    Enabled: true
    Frequency: 100
    Factor: 5.0
    Element: Fire
    Time: Day
Abilities:
  AvatarStateOnFinalBlow: true
ElementAssign:
  Enabled: true
  Default: Earth
  Percentages:
    Air: 0.205
    Fire: 0.205
    Water: 0.205
    Earth: 0.205
    Chi: 0.18