WorldEvents:
  FullMoon:
    Enabled: true
    Factor: 3.0
    Element: Water
    Message: A full moon is rising, empowering waterbending like never before.
  SolarEclipse:
    Enabled: true
    Frequency: 20
    Element: Fire
    Message: A lunar eclipse is out! Waterbenders are temporarily powerless.
  LunarEclipse:
    Enabled: true
    Frequency: 40
    Element: Water
    Message: A solar eclipse is out! Firebenders are temporarily powerless.
  SozinsComet:
    Enabled: true
    Frequency: 100
    Factor: 5.0
    Element: Fire
    Message: Sozin's Comet is passing overhead! Firebending is now at its most powerful.
    EndMessage: Sozin's Comet has passed.
Abilities:
  AvatarStateOnFinalBlow: true
ElementAssign:
  Enabled: false
  Default: None
  Percentages:
    Air: 0.205
    Fire: 0.205
    Water: 0.205
    Earth: 0.205
    Chi: 0.18
Storage:
  engine: sqlite
  MySQL:
    host: localhost
    port: 3306
    pass: ''
    db: minecraft
    user: root