name: ProjectKorraRPG
author: ProjectKorra
version: 1.0.0
main: com.projectkorra.rpg.ProjectKorraRPG
softdepend: [ProjectKorra]
description: RPG side-plugin for ProjectKorra core
permissions:
  bending.rpg.admin:
    default: op
    children:
      bending.rpg.command.avatar: true
      bending.rpg.command.worldevent.*: true
  bending.rpg.command.avatar:
    default: op
  bending.rpg.command.help:
    default: true
  bending.rpg.command.worldevent:
    default: true
    children:
      bending.rpg.command.worldevent.current: true
      bending.rpg.command.worldevent.end: false
      bending.rpg.command.worldevent.skip: false
      bending.rpg.command.worldevent.noskip: false
      bending.rpg.command.worldevent.start: false